#pragma once

#define WORLD_GRAVITY b2Vec2(0.0, -10.0)
#define WORLD_VELOCITY_ITERATIONS 8
#define WORLD_POSITION_ITERATIONS 3

#define EPSILON 1E-6

#define PAD_SPAWNTIME 1.2f
#define PAD_VELOCITY -3.0f
#define IMPULSE_FIRSTJUMP 5.5f
#define IMPULSE_SECONDJUMP 6.0f